delimiter ;
DROP SCHEMA IF EXISTS `bookstore`; 
CREATE SCHEMA `bookstore` ;
use `bookstore`;

CREATE TABLE `customer` (
  `custId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`custId`)
);

CREATE TABLE `category` (
  `catId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`catId`)
);

CREATE TABLE `product` (
  `prodId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `catId` INT NOT NULL,
  PRIMARY KEY (`prodId`),
  INDEX `prod_cat_FK_idx` (`catId` ASC),
  CONSTRAINT `prod_cat_FK`
    FOREIGN KEY (`catId`)
    REFERENCES `category` (`catId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE `orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `custId` INT NOT NULL,
  `subtotal` DECIMAL(11,3) NULL,
  `tax` DECIMAL(6,2) NULL,
  `total` DECIMAL(15,3) NULL,
  PRIMARY KEY (`orderId`),
  INDEX `order_cust_FK_idx` (`custId` ASC),
  CONSTRAINT `order_cust_FK`
    FOREIGN KEY (`custId`)
    REFERENCES `customer` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE `orderitem` (
  `orderItemId` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) NOT NULL,
  `prodId` int(11) NOT NULL,
  `quantity` int(11) NOT NULL,
  PRIMARY KEY (`orderItemId`),
  KEY `orderItem_product_FK_idx` (`prodId`),
  KEY `orderItem_order_FK` (`orderId`),
  CONSTRAINT `orderItem_order_FK` FOREIGN KEY (`orderId`) REFERENCES `orders` (`orderId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `orderItem_product_FK` FOREIGN KEY (`prodId`) REFERENCES `product` (`prodId`) ON DELETE NO ACTION ON UPDATE NO ACTION
); 


CREATE TABLE `inventory` (
  `invId` INT NOT NULL AUTO_INCREMENT,
  `prodId` INT NOT NULL,
  `initialCount` INT NOT NULL,
  `availableCount` INT NOT NULL,
  `soldCount` INT NOT NULL,
  `sellingDetails` VARCHAR(45) NULL,
  PRIMARY KEY (`invId`),
  UNIQUE INDEX `prodId_UNIQUE` (`prodId` ASC),
  CONSTRAINT `Inventory_Prod_FK` FOREIGN KEY (`prodId`) REFERENCES `product` (`prodId`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


INSERT INTO CUSTOMER (`NAME`,`STATE`) VALUES ( 'JOHN', 'CA');
INSERT INTO CUSTOMER (`NAME`,`STATE`) VALUES ( 'JACK', 'FL');
INSERT INTO CUSTOMER (`NAME`,`STATE`) VALUES ( 'ROSS', 'IL');
INSERT INTO CUSTOMER (`NAME`,`STATE`) VALUES ( 'JOEY', 'IN');
INSERT INTO CUSTOMER (`NAME`,`STATE`,`PASSWORD`) VALUES ( 'rachel', 'CA','green');

INSERT INTO CATEGORY (`name`) VALUES (	'Biography');
INSERT INTO CATEGORY (`name`) VALUES (	"Children's Books");
INSERT INTO CATEGORY (`name`) VALUES (	'Comics');
INSERT INTO CATEGORY (`name`) VALUES (	'Computers and Technology');
INSERT INTO CATEGORY (`name`) VALUES (	'Education and Learning');
INSERT INTO CATEGORY (`name`) VALUES (	'Literature and Fiction');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Steve Jobs','1', '11.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Einstein: His Life and Universe ','1', '13.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future','1', '18.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Lean In: Women, Work, and the Will to Lead','1', '14.85');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Big Short: Inside the Doomsday Machine','1', '17.33');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Unbroken: A World War II Story of Survival, Resilience, and Redemption','1', '10.88');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Harry Potter and the Sorcerer's Stone",'2', '11.73');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Mockingjay (Hunger Games Trilogy, Book 3)','2', '10.73');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Hobbit (Lord of the Rings)','2', '10.63');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Catching Fire (Hunger Games Trilogy, Book 2)','2', '8.94');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Prisoner of Azkaban','2', '15.04');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Deathly Hallows','2', '21.34');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Order of the Phoenix','2', '18.29');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Hunger Games (Hunger Games Trilogy, Book 1)','2', '10.73');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Goblet of Fire','2', '18.28');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Chamber of Secrets','2', '15.24');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Harry Potter and the Half-Blood Prince','2', '16.94');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Batman: The Killing Joke','3', '10.16');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "The Hitchhiker's Guide to the Galaxy",'3', '8.48');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Walking Dead: Compendium Three','3', '34.88');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Walking Dead: Compendium One','3', '35.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Walking Dead: Compendium Two','3', '33.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Civil War','3', '14.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Fun Home: A Family Tragicomic','3', '8.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Super Mario: The Funniest Super Mario Jokes & Memes Volume 2','3', '8.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Cross and the Switchblade','3', '13.99');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Java: A Beginner's Guide, Sixth Edition",'4', '20.96');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Hadoop: The Definitive Guide",'4', '36	.48');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Professional Java Development with the Spring Framework','4', '28.88');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Windows 10 For Seniors For Dummies','4', '14.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'HTML and CSS: Design and Build Websites','4', '18.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'JavaScript and JQuery: Interactive Front-End Web Development','4', '27.27');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Python Machine Learning','4', '29.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Clean Code: A Handbook of Agile Software Craftsmanship','4', '28.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Head First Java, 2nd Edition','4', '26.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Linux Command Line: A Complete Introduction','4', '26.31');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'iPhone For Seniors For Dummies','4', '20.99');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Official SAT Study Guide (2016 Edition)",'5', '18.41');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Official GRE Super Power Pack",'5', '36.48');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Step-Up to Medicine (Step-Up Series)','5', '22.88');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The PowerScore LSAT Logical Reasoning Bible','5', '16.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Official TOEFL iBT Tests Volume 2','5', '20.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "Barron's IELTS Superpack",'5', '24.27');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Teach Your Child to Read in 100 Easy Lessons','5', '15.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( "The Artist's Way",'5', '10.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'GMAT 2016 Official Guide Bundle','5', '80.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Kaplan GMAT Math Workbookn','5', '14.31');

INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Girl on the Train: A Novel','6', '9.41');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Black Widow','6', '16.48');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'A Man Called Ove: A Novel','6', '9.52');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Nightingale','6', '13.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Between the World and Me','6', '12.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'After You: A Novel','6', '9.27');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'Me Before You: A Novel','6', '6.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'All the Light We Cannot See','6', '16.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Alchemist','6', '10.99');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Light Between Oceans','6', '9.31');
INSERT INTO PRODUCT (`NAME`,`CATID`,`PRICE`)  VALUES ( 'The Book Thief','6', '7.31');


INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (1, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (2, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (3, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (4, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (5, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (6, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (7, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (8, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (9, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (10, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (11, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (12, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (13, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (14, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (15, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (16, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (17, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (18, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (19, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (20, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (21, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (22, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (23, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (24, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (25, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (26, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (27, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (28, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (29, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (30, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (31, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (32, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (33, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (34, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (35, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (36, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (37, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (38, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (39, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (40, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (41, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (42, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (43, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (44, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (45, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (46, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (47, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (48, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (49, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (50, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (51, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (52, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (53, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (54, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (55, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (56, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (57, 50, 50, 0);
INSERT INTO INVENTORY (`PRODID`, `INITIALCOUNT`, `AVAILABLECOUNT`, `SOLDCOUNT`) VALUES (58, 50, 50, 0);



